import type { Metadata } from "next";

import "./globals.css";
import RQProvider from "./providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased  bg-[#141b23]`}>
        <RQProvider>
          {children}
        </RQProvider>
      </body>
    </html>
  );
}
